### ISSUE TITLE
Firebase json

### ISSUE THREAD

**Issue by hackerspace-studio** [rootasjey/fig.style#6]
I understand that there is no json database backup in the code?
How can you interact with data? only through your base?

**Comment by rootasjey** [comment]
# Database
If you just want to interact with the database, you can try the early REST API. The API is in early stage, and I haven't built a documentation yet. But you can create a developer account and app at: [dev.fig.style](https://dev.fig.style).

The quote of the day (quotidian) endpoint can be used right away:

* [api.fig.style/v1/quotidian](https://api.fig.style/v1/quotidian)

But the other endpoints require key authorization:

> Key authorization can be set with "__?apikey=xxx__" query string or "__authorization__" header.
> All following endpoints must have the __api.fig.style/v1/__ prefix.

* quotes
  * [__quotes/__](api.fig.style/v1/quotes/) : get the last 12 quotes
  * [__quotes/:id__](api.fig.style/v1/quotes/xuDzX6wrHJJ2E1jOqLNA) : get a specific quote from its id
  * [__quotes/random__](api.fig.style/v1/quotes/random) : get 12 random quotes

There are also endpoints for [authors](https://api.fig.style/v1/authors), [references](https://api.fig.style/v1/references), [search](https://api.fig.style/v1/search), and [topics](https://api.fig.style/v1/topics). Let me know if you plan to use the API, so I may build the API documentation in priority.

# Contributing
If you want to run this app locally, you won't be able because of the missing `firebsaejson` file. I plan to create a branch which uses the API instead of the `firebase.json`, but it may take some months.

**Comment by hackerspace-studio** [comment]
I understood everything, thanks )
